test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.game="minetest_game"
	args.servername="packagecheck"
	args.pvp=1
	args.creative=0
	args.damage=1
