#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	ynh_clean_check_starting # Need for the param line_match of ynh_systemd_action
}

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get --app=$app --key=final_path)
domain=$(ynh_app_setting_get --app=$app --key=domain)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
# Stop Minetest before backup...
ynh_systemd_action --action=stop

ynh_print_info --message="Backing up the main app directory..."

ynh_backup --src_path="$final_path"

#=================================================
# BACKUP THE HOME DIR
#=================================================
ynh_print_info --message="Backing up Minetest data..."

ynh_backup --src_path="/home/yunohost.app/$app"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================
ynh_print_info --message="Backing up logrotate configuration..."

ynh_backup --src_path="/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD
#=================================================
ynh_print_info --message="Backing up systemd configuration..."

ynh_backup --src_path="/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================
# Restart Minetest
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
