#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If game doesn't exist, create it
ynh_app_setting_set_default --key=game --value="minetest_game"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building $app..."

# Install the game
ynh_setup_source --dest_dir=$install_dir/games/$game --source_id=$game

pushd $install_dir
	ynh_hide_warnings cmake . -DRUN_IN_PLACE=TRUE -DENABLE_LUAJIT=TRUE -DBUILD_CLIENT=FALSE -DBUILD_SERVER=TRUE
	ynh_hide_warnings make -j$(nproc)
popd

#=================================================
# COPY CONFIG FILE
#=================================================

if [ -e $data_dir ]
	then
		echo "Nothing to do..."
	else
		mkdir -p $data_dir/.luanti/
		mkdir $data_dir/.luanti/worlds/
fi

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="luanti.conf" --destination="$data_dir/.luanti/luanti.conf"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="Voxel game engine and game" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --wait_until="listening on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
